</$PLAN9/src/mkhdr

TARG=samterm
OFILES=main.$O\
	icons.$O\
	menu.$O\
	mesg.$O\
	rasp.$O\
	scroll.$O\
	flayer.$O\
	io.$O\
	plan9.$O\

HFILES=samterm.h\
	flayer.h\
	../sam/sam.h\
	../sam/mesg.h\
	$PLAN9/include/frame.h\

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

CFLAGS=$CFLAGS -I../sam

<$PLAN9/src/mkone

CFLAGS=-I../sam $CFLAGS

mesg.$O:	../sam/mesg.h

syms:V:
	$CC -a $CFLAGS main.c		 > syms
	for(i in *.c) $CC -aa $CFLAGS $i >> syms
